import type { Metadata } from 'next'
import './ui/globals.css'
import { montserrat } from './ui/font'

export const metadata: Metadata = {
  title: 'Connecto | Social University',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={montserrat.className}>

        {children}</body>
    </html>
  )
}
