version: "3.9"

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 5173:5173
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production

  db:
    container_name: connecto
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: connecto
      POSTGRES_PASSWORD: conectdb
      POSTGRES_DB: connecto
    ports:
      - 5432:5432


    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}



#     volumes:
#       - pgdataconnect:/var/lib/postgresql/data

# volumes:
#   pgdataconnect: {}


