
version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000


  db:
    container_name: connecto
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: connecto
      POSTGRES_PASSWORD: conectdb
      POSTGRES_DB: connecto
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}


# version: '3.9'

# services:
#   frontend:
#     container_name: frontend
#     image: frontend
#     build:  
#       context: ./frontend
#       dockerfile: frontend.dockerfile
#     ports:
#       -  3000:3000
#     volumes:
#       - ./frontend:/app # Monta el directorio local en el contenedor
#       - node_modules:/app/node_modules

#     command: pnpm run dev # Comando para iniciar en modo de desarrollo
#     depends_on:
#       - backend

#   backend:
#     container_name: backend
#     image: backend
#     build:
#       context: ./backend
#       dockerfile: backend.dockerfile
#     ports:
#       -  4000:4000
#     volumes:
#       - ./backend:/app # Monta el directorio local en el contenedor
#     depends_on:
#       - db

#   db:
#     container_name: connecto
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_USER: connecto
#       POSTGRES_PASSWORD: conectdb
#       POSTGRES_DB: connecto
#     ports:
#       -  5432:5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}
#   node_modules: {}

